name: "auto assign reviewers"
on:
  - pull_request

jobs:
  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        config: '.github/reviewers.yml'
        token: ${{ secrets.GITHUB_TOKEN }}
